In [1]:
# Ch4. numpy

In [2]:
import numpy as np

my_arr=np.arange(1000000)
my_list=list(range(1000000))

In [3]:
%time for _ in range(10): my_arr2=my_arr*2

In [4]:
%time for _ in range(10): my_list2=[x*2 for x in my_list]

Wall time: 989 ms


In [5]:
data = np.random.randn(2,3)

In [6]:
data

array([[-0.84280559, -0.03312282, -0.62202054],
       [ 1.05204759, -0.33877308,  1.77330643]])

In [7]:
data*10

array([[-8.42805592, -0.33122822, -6.22020538],
       [10.52047587, -3.38773082, 17.73306434]])

In [8]:
data+data

array([[-1.68561118, -0.06624564, -1.24404108],
       [ 2.10409517, -0.67754616,  3.54661287]])

In [9]:
data.shape  # 차원의 크기를 알려주는 Shape라는 튜플

(2, 3)

In [10]:
data.dtype  # 자료형을 알려주는 dtype라는 객체

dtype('float64')

In [11]:
data1=[6,7.5,8,0,1]
arr1=np.array(data1)

In [12]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [13]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)

In [14]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
arr2.ndim  # 배열의 차원 수 or 배열의 축 수

2

In [16]:
arr2.shape

(2, 4)

In [17]:
arr1.dtype

dtype('float64')

In [18]:
arr2.dtype

dtype('int32')

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [22]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
arr1=np.array([1,2,3],dtype=np.float64)

In [24]:
arr2=np.array([1,2,3],dtype=np.int32)

In [25]:
arr1.dtype

dtype('float64')

In [26]:
arr2.dtype

dtype('int32')

In [27]:
arr=np.array([1,2,3,4,5])

In [28]:
arr.dtype

dtype('int32')

In [29]:
float_arr=arr.astype(np.float64)

In [30]:
float_arr.dtype

dtype('float64')

In [31]:
float_arr

array([1., 2., 3., 4., 5.])

In [32]:
arr=np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])

In [33]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [34]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [35]:
numeric_strings=np.array(['1.25','-9.6','42'],dtype=np.string_)

In [36]:
numeric_strings.astype(float)  # np.float64 형태로 입력하여도 무방

array([ 1.25, -9.6 , 42.  ])

+ 숫자형식의 문자열을 담고있는 배열일 경우에만 가능하다.

In [37]:
int_array=np.arange(10)

In [38]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
calibers=np.array([.22,.270,.357,.380,.44,.50],dtype=np.float64)

In [40]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
empty_unit32=np.empty(8,dtype='u4')

In [42]:
empty_unit32

# empty는 초기화되지 않은 값으로 zeros와 ones와 마찬가지로 배열을 생성
# 주의해야 할 것은 갈비지 값

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [43]:
arr=np.array([[1.,2.,3.],[4.,5.,6.]])

In [44]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [45]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [46]:
arr.dtype

dtype('float64')

In [47]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [49]:
arr**0.5  # **은 거듭제곱 연산자

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [50]:
arr2=np.array([[0.,4.,1],[7.,2.,12.]])

In [51]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [52]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [53]:
arr=np.arange(10)

In [54]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr[5]

5

In [56]:
arr[5:8]

array([5, 6, 7])

In [57]:
arr[5:8]=12  # 배열 조각에 스칼라값을 대입하면 선택 영역 전체로 전파(브로드캐스팅)

In [58]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [59]:
arr_slice=arr[5:8]

In [60]:
arr_slice

array([12, 12, 12])

In [61]:
arr_slice[1]=12345

In [62]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [63]:
arr_slice

array([   12, 12345,    12])

In [64]:
arr_slice[:]=64  # 배열 모든 값을 할당

In [65]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [66]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [67]:
arr2d[2]

array([7, 8, 9])

In [68]:
arr2d[0][2]

3

In [69]:
arr2d[0,2]  # 위와 동일한 표현이다.

3

In [70]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [71]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
ond_value=arr3d[0].copy()

In [74]:
arr3d[0]=42

In [75]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [76]:
arr3d[1,0]

array([7, 8, 9])

In [77]:
x=arr3d[1]

In [78]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [79]:
x[0]

array([7, 8, 9])

In [80]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [81]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [82]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [85]:
arr2d[1,:2]

array([4, 5])

In [86]:
arr2d[:2,2]

array([3, 6])

In [87]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [88]:
arr2d[:2,1:]=0

In [89]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [90]:
names=np.array(['Bob',"Joe","Wil",'Bob','Will',"Joe","Joe"])

In [91]:
data=np.random.randn(7,4)

In [92]:
names

array(['Bob', 'Joe', 'Wil', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [93]:
data

array([[ 0.91384798,  0.13117244, -0.47619753, -0.93578635],
       [ 1.39434135, -0.02885079, -0.44287304,  0.63746059],
       [ 1.52894718,  0.42662612,  0.32200741, -0.28481754],
       [-0.82927718,  1.76829362,  1.36298002,  0.18600518],
       [-0.62990889, -1.78080193,  2.98336974,  0.78419865],
       [-0.69683215,  1.29262944, -0.50887309,  0.37495939],
       [ 1.54862664,  1.02760942,  1.72203815, -0.43335729]])

In [94]:
names=="Bob"

array([ True, False, False,  True, False, False, False])

In [95]:
data[names=='Bob']

array([[ 0.91384798,  0.13117244, -0.47619753, -0.93578635],
       [-0.82927718,  1.76829362,  1.36298002,  0.18600518]])

In [96]:
data[names=='Joe']

array([[ 1.39434135, -0.02885079, -0.44287304,  0.63746059],
       [-0.69683215,  1.29262944, -0.50887309,  0.37495939],
       [ 1.54862664,  1.02760942,  1.72203815, -0.43335729]])

In [97]:
data[names=='Bob',2:]

array([[-0.47619753, -0.93578635],
       [ 1.36298002,  0.18600518]])

In [98]:
data[names=='Bob',3]

array([-0.93578635,  0.18600518])

In [99]:
names !='Bob'  3   #!= 부정 

SyntaxError: invalid syntax (<ipython-input-99-b536b671913d>, line 1)

In [100]:
cond=names=="Bob"

In [101]:
data[~cond]

array([[ 1.39434135, -0.02885079, -0.44287304,  0.63746059],
       [ 1.52894718,  0.42662612,  0.32200741, -0.28481754],
       [-0.62990889, -1.78080193,  2.98336974,  0.78419865],
       [-0.69683215,  1.29262944, -0.50887309,  0.37495939],
       [ 1.54862664,  1.02760942,  1.72203815, -0.43335729]])

In [102]:
mask=((names=='Bob')|(names=="Will"))

In [103]:
mask

array([ True, False, False,  True,  True, False, False])

In [104]:
data[mask]

array([[ 0.91384798,  0.13117244, -0.47619753, -0.93578635],
       [-0.82927718,  1.76829362,  1.36298002,  0.18600518],
       [-0.62990889, -1.78080193,  2.98336974,  0.78419865]])

In [105]:
data[data<0]=0

In [106]:
data

array([[0.91384798, 0.13117244, 0.        , 0.        ],
       [1.39434135, 0.        , 0.        , 0.63746059],
       [1.52894718, 0.42662612, 0.32200741, 0.        ],
       [0.        , 1.76829362, 1.36298002, 0.18600518],
       [0.        , 0.        , 2.98336974, 0.78419865],
       [0.        , 1.29262944, 0.        , 0.37495939],
       [1.54862664, 1.02760942, 1.72203815, 0.        ]])

In [107]:
arr=np.empty((8,4))

In [108]:
for i in range(8):
    arr[i]=i

In [109]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [110]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [111]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [112]:
arr=np.arange(32).reshape((8,4))

In [113]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [114]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [115]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [116]:
arr=np.arange(15).reshape(3,5)

In [117]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [118]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [119]:
arr=np.random.randn(6,3)

In [120]:
arr

array([[-0.87110223, -0.72744013, -1.37927998],
       [ 1.4139756 ,  0.6204411 ,  0.0215299 ],
       [-0.47688474, -0.25653817,  0.36411304],
       [ 0.33583696,  1.17671697,  1.07010319],
       [-1.10909834, -0.18489616,  0.6176105 ],
       [ 2.16763908,  0.44387601, -0.46787906]])

In [121]:
np.dot(arr.T,arr)  # 행렬의 내적

array([[ 9.02710992,  3.1957185 , -0.28150685],
       [ 3.1957185 ,  2.59580348,  1.86062724],
       [-0.28150685,  1.86062724,  3.78092948]])

In [122]:
arr=np.arange(16).reshape((2,2,4))

In [123]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [124]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [125]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [126]:
arr=np.arange(10)

In [127]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [129]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [130]:
x=np.random.randn(8)

In [131]:
y=np.random.randn(8)

In [132]:
x

array([-0.97515064, -1.95644993,  0.40624109, -0.67488006,  0.30155863,
       -0.13191642,  0.72357479, -0.91276761])

In [133]:
y

array([ 0.58230767, -0.12727573, -1.50300229, -1.17788223,  0.41998865,
        0.29893815,  0.94159133,  1.04538356])

In [134]:
np.maximum(x,y)

array([ 0.58230767, -0.12727573,  0.40624109, -0.67488006,  0.41998865,
        0.29893815,  0.94159133,  1.04538356])

In [135]:
arr=np.random.randn(7)*5

In [136]:
arr

array([ 1.13624449, -3.16696946, 11.97429548, -3.20135316,  5.44958996,
        5.43866371,  2.89722832])

In [137]:
remainder,whole_part=np.modf(arr)

In [138]:
remainder

array([ 0.13624449, -0.16696946,  0.97429548, -0.20135316,  0.44958996,
        0.43866371,  0.89722832])

In [139]:
whole_part

array([ 1., -3., 11., -3.,  5.,  5.,  2.])

In [140]:
np.sqrt(arr)

<ipython-input-140-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([1.06594769,        nan, 3.4603895 ,        nan, 2.33443568,
       2.33209427, 1.70212465])

In [141]:
np.sqrt(arr,arr)

<ipython-input-141-e3ca18b15869>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr,arr)


array([1.06594769,        nan, 3.4603895 ,        nan, 2.33443568,
       2.33209427, 1.70212465])

In [142]:
arr

array([1.06594769,        nan, 3.4603895 ,        nan, 2.33443568,
       2.33209427, 1.70212465])