A.5 Structed and Record Arrays

In [2]:
import numpy as np

In [3]:
dtype=[('x',np.float64),('y',np.int32)]

In [4]:
sarr=np.array([(1.5,6),(np.pi,-2)],dtype=dtype)

In [5]:
sarr

array([(1.5       ,  6), (3.14159265, -2)],
      dtype=[('x', '<f8'), ('y', '<i4')])

In [6]:
sarr[0]

(1.5, 6)

In [7]:
sarr[0]['y']

6

In [8]:
sarr['x']

array([1.5       , 3.14159265])

In [9]:
dtype=[('x',np.int64,3),('y',np.int32)]

In [10]:
arr=np.zeros(4,dtype=dtype)

In [11]:
arr

array([([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0)],
      dtype=[('x', '<i8', (3,)), ('y', '<i4')])

In [12]:
arr[0]['x']

array([0, 0, 0], dtype=int64)

In [13]:
arr['x']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [19]:
dtype=[('x',[('a','f8'),('b','f4')]),('y',np.int32)]

In [20]:
data=np.array([((1,2),5),((3,4),6)],dtype=dtype)

In [21]:
data['x']

array([(1., 2.), (3., 4.)], dtype=[('a', '<f8'), ('b', '<f4')])

In [22]:
data['y']

array([5, 6])

In [23]:
data['x']['a']

array([1., 3.])

A.6 More About Sorting

In [24]:
arr=np.random.randn(6)

In [25]:
arr

array([ 0.08892211, -0.22401746,  0.44220453,  0.28726632, -0.52650629,
       -0.61376236])

In [26]:
arr.sort()

In [27]:
arr

array([-0.61376236, -0.52650629, -0.22401746,  0.08892211,  0.28726632,
        0.44220453])

In [28]:
arr=np.random.randn(3,5)

In [29]:
arr

array([[-0.6010325 , -0.46844273, -0.06846105,  0.40398333, -1.02667002],
       [-0.11036801,  0.64713862, -0.02800813,  0.96491763,  0.14137958],
       [-0.31621373,  1.0885809 ,  1.20991961,  0.21671178, -0.23163025]])

In [30]:
arr[:,0].sort()

In [31]:
arr

array([[-0.6010325 , -0.46844273, -0.06846105,  0.40398333, -1.02667002],
       [-0.31621373,  0.64713862, -0.02800813,  0.96491763,  0.14137958],
       [-0.11036801,  1.0885809 ,  1.20991961,  0.21671178, -0.23163025]])

In [32]:
arr=np.random.randn(5)

In [33]:
arr

array([ 0.82056073,  0.33380373, -0.08209153,  0.3981583 , -1.16769851])

In [34]:
np.sort(arr)

array([-1.16769851, -0.08209153,  0.33380373,  0.3981583 ,  0.82056073])

In [36]:
arr

array([ 0.82056073,  0.33380373, -0.08209153,  0.3981583 , -1.16769851])

In [37]:
arr=np.random.randn(3,5)

In [38]:
arr

array([[ 1.90125235,  0.1748216 , -0.40191341, -0.28325606, -0.28336232],
       [-0.03915036, -0.29810039, -0.09476312, -1.27243605,  1.18128631],
       [ 0.68850042, -0.14098863, -1.1236948 ,  1.33687918,  0.92287829]])

In [39]:
arr.sort(axis=1)

In [40]:
arr

array([[-0.40191341, -0.28336232, -0.28325606,  0.1748216 ,  1.90125235],
       [-1.27243605, -0.29810039, -0.09476312, -0.03915036,  1.18128631],
       [-1.1236948 , -0.14098863,  0.68850042,  0.92287829,  1.33687918]])

In [41]:
arr[:,::-1]

array([[ 1.90125235,  0.1748216 , -0.28325606, -0.28336232, -0.40191341],
       [ 1.18128631, -0.03915036, -0.09476312, -0.29810039, -1.27243605],
       [ 1.33687918,  0.92287829,  0.68850042, -0.14098863, -1.1236948 ]])

In [42]:
values=np.array([5,0,1,3,2])

In [43]:
indexer=values.argsort()

In [44]:
indexer

array([1, 2, 4, 3, 0], dtype=int64)

In [45]:
values[indexer]

array([0, 1, 2, 3, 5])

In [46]:
arr=np.random.randn(3,5)

In [47]:
arr[0]

array([ 0.51024437, -0.63231929,  0.03882016,  1.91875075, -0.45079801])

In [48]:
arr[:,arr[0].argsort()]

array([[-0.63231929, -0.45079801,  0.03882016,  0.51024437,  1.91875075],
       [-0.63129114, -1.21112704,  0.98032689,  0.6450703 ,  1.12847671],
       [-0.28621347, -0.22094047,  0.39322957,  0.74489418,  0.53268343]])

In [49]:
first_name=np.array(['Bob','Jane','Steve','Bill','Barbara'])

In [50]:
last_name=np.array(['Jones','Arnold','Arnold','Jones','Walters'])

In [52]:
sorter=np.lexsort((first_name,last_name))

In [53]:
sorter

array([1, 2, 3, 0, 4], dtype=int64)

In [54]:
values=np.array(['2:first','2:second','1:first','1:second','1:third'])

In [55]:
key=np.array([2,2,1,1,1])

In [56]:
indexer=key.argsort(kind='mergesort')

In [57]:
indexer

array([2, 3, 4, 0, 1], dtype=int64)

In [59]:
values.take(indexer)

array(['1:first', '1:second', '1:third', '2:first', '2:second'],
      dtype='<U8')

In [60]:
np.random.seed(12345)

In [61]:
arr=np.random.randn(20)

In [62]:
arr

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057,
        1.39340583,  0.09290788,  0.28174615,  0.76902257,  1.24643474,
        1.00718936, -1.29622111,  0.27499163,  0.22891288,  1.35291684,
        0.88642934, -2.00163731, -0.37184254,  1.66902531, -0.43856974])

In [63]:
np.partition(arr,3)

array([-2.00163731, -1.29622111, -0.5557303 , -0.51943872, -0.37184254,
       -0.43856974, -0.20470766,  0.28174615,  0.76902257,  0.47894334,
        1.00718936,  0.09290788,  0.27499163,  0.22891288,  1.35291684,
        0.88642934,  1.39340583,  1.96578057,  1.66902531,  1.24643474])

In [66]:
indices=np.argpartition(arr,3)

In [67]:
indices

array([16, 11,  3,  2, 17, 19,  0,  7,  8,  1, 10,  6, 12, 13, 14, 15,  5,
        4, 18,  9], dtype=int64)

In [68]:
indices=np.argpartition(arr,3)

In [69]:
indices

array([16, 11,  3,  2, 17, 19,  0,  7,  8,  1, 10,  6, 12, 13, 14, 15,  5,
        4, 18,  9], dtype=int64)

In [70]:
arr.take(indices)

array([-2.00163731, -1.29622111, -0.5557303 , -0.51943872, -0.37184254,
       -0.43856974, -0.20470766,  0.28174615,  0.76902257,  0.47894334,
        1.00718936,  0.09290788,  0.27499163,  0.22891288,  1.35291684,
        0.88642934,  1.39340583,  1.96578057,  1.66902531,  1.24643474])

In [71]:
arr=np.array([0,1,7,12,15])

In [72]:
arr.searchsorted(9)

3

In [73]:
arr.searchsorted([0,8,11,16])

array([0, 3, 3, 5], dtype=int64)

In [74]:
arr=np.array([0,0,0,1,1,1,1])

In [75]:
arr.searchsorted([0,1])

array([0, 3], dtype=int64)

In [76]:
arr.searchsorted([0,1],side='right')

array([3, 7], dtype=int64)

In [77]:
data=np.floor(np.random.uniform(0,10000,size=50))

In [78]:
bins=np.array([0,100,1000,5000,10000])

In [79]:
data

array([9940., 6768., 7908., 1709.,  268., 8003., 9037.,  246., 4917.,
       5262., 5963.,  519., 8950., 7282., 8183., 5002., 8101.,  959.,
       2189., 2587., 4681., 4593., 7095., 1780., 5314., 1677., 7688.,
       9281., 6094., 1501., 4896., 3773., 8486., 9110., 3838., 3154.,
       5683., 1878., 1258., 6875., 7996., 5735., 9732., 6340., 8884.,
       4954., 3516., 7142., 5039., 2256.])

In [80]:
labels=bins.searchsorted(data)

In [81]:
labels

array([4, 4, 4, 3, 2, 4, 4, 2, 3, 4, 4, 2, 4, 4, 4, 4, 4, 2, 3, 3, 3, 3,
       4, 3, 4, 3, 4, 4, 4, 3, 3, 3, 4, 4, 3, 3, 4, 3, 3, 4, 4, 4, 4, 4,
       4, 3, 3, 4, 4, 3], dtype=int64)

In [82]:
len(data)

50

In [83]:
len(labels)

50

More on the IPytion System

In [84]:
2**27

134217728

In [85]:
_

134217728

In [86]:
__

134217728

In [87]:
3

3

In [88]:
_

3

In [89]:
__

3

In [90]:
foo='bar'

In [91]:
foo

'bar'

In [94]:
_i91

'foo'

In [95]:
_91

'bar'

In [96]:
%hist

dtype=[('x',np.float64),('y',np.int32)]
import numpy as np
dtype=[('x',np.float64),('y',np.int32)]
sarr=np.array([(1.5,6),(np.pi,-2)],dtype=dtype)
sarr
sarr[0]
sarr[0]['y']
sarr['x']
dtype=[('x',np.int64,3),('y',np.int32)]
arr=np.zeros(4,dtype=dtype)
arr
arr[0]['x']
arr['x']
dtype=[('x',[('a','f8'),('b','f4')],('y',np,int32))]
dtype=[('x',[('a','f8'),('b','f4')],('y',np.int32))]
data['x']
data=np.array([((1,2),5),((3,4),6)],dtype=dtype)
data=np.array([((1,2),5),((3,4),6)],dtype=dtype)
dtype=[('x',[('a','f8'),('b','f4')]),('y',np.int32)]
data=np.array([((1,2),5),((3,4),6)],dtype=dtype)
data['x']
data['y']
data['x']['a']
arr=np.random.randn(6)
arr
arr.sort()
arr
arr=np.random.randn(3,5)
arr
arr[:,0].sort()
arr
arr=np.random.randn(5)
arr
np.sort(arr)
}arr
arr
arr=np.random.randn(3,5)
arr
arr.sort(axis=1)
arr
arr[:,::-1]
values=np.array([5,0,1,3,2])
indexer=values.argsort()
indexer
values[indexer]
arr=np.random.randn(3,5)
arr[0]
arr[:,arr[0].argsort()]
first_name=np.array(['Bob','Jane','St

In [97]:
a='10'

In [98]:
a

'10'

In [99]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [100]:
a

NameError: name 'a' is not defined

Timing Code: %time and %timeit

In [108]:
import time
start=time.time()

In [111]:
strings=['foo','foobar','baz','qux','python','Guido Van Rossum']*100000

In [112]:
method1=[x for x in strings if x.startswith('foo')]

In [113]:
method2=[x for x in strings if x[:3]=='foo']

In [114]:
%time method1 =[x for x in strings if x.startswith('foo')]

Wall time: 125 ms


In [116]:
%time mthod2=[x for x in strings if x[:3]=='foo']

Wall time: 135 ms


In [118]:
%timeit [x for x in strings if x.startswith('foo')]

118 ms ± 15.9 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [119]:
%timeit [x for x in strings if x[:3]=='foo']

109 ms ± 6.42 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [120]:
x='foobar'
y='foo'

In [121]:
%timeit x.startswith(y)

252 ns ± 14.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [122]:
%timeit x[:3]==y

239 ns ± 26.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
