A.1 ndarray 객체 구조

In [1]:
import numpy as np

In [2]:
a=np.ones((10,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
np.ones((10,5)).shape
# shape이라는 함수를 사용해서 배열의 크기를 알아낼 수 있다.

(10, 5)

In [4]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [5]:
np.ones((3,4,5),dtype=np.float64).strides
# (4*5*8,5*8,1*8) float64는 8바이트 이기 때문이다.
# 이 때 strides 값이 음수이면 뒤로 이동하는 의미이다.

(160, 40, 8)

A.1.1 NumPy dtype 구조

In [6]:
ints=np.ones(10,dtype=np.uint16)

In [7]:
floats=np.ones(10,dtype=np.float32)

In [8]:
np.issubdtype(ints.dtype,np.integer)

True

In [9]:
np.issubdtype(floats.dtype,np.floating)

True

배열에 담긴 값의 datatype을 확인해야 할 필요가 있음.
실수에도 다양한 형태가 있다. dtype은 np.issubtype 함수와 결합하여 사용할 수 있는 np.integer나 np.floating 같은 부모 클래스를 가진다.

In [10]:
np.float64.mro()
# 부모 클래스는 mro 메서드를 사용해서 알 수 있다.

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [11]:
np.issubdtype(ints.dtype,np.number)

True

A.2 고급 배열 조작 기법

A.2.1 배열 재형성하기

In [12]:
arr=np.arange(8)

In [13]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [14]:
b=arr.reshape((4,2))
b
# reshape 함수를 사용해서 배열의 모양을 변환

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [15]:
c=arr.reshape((4,2),order='C')
c
# 'C' 로우 우선

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [16]:
d=arr.reshape((4,2),order='F')
d
# 'F' 컬럼 우선

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [17]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [18]:
arr.reshape((4,2)).reshape((2,4))
# 다차원 배열 또한 재형성이 가능하다

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [19]:
arr=np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
arr.reshape((5,-1))
# reshape에 넘기는 값 중 하나가 -1이 될 수 도 있는데 이 경우
# 원본 데이터를 참조해서 적절한 값을 추론

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [21]:
other_arr=np.ones((3,5))
other_arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
other_arr.shape

(3, 5)

In [23]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

배열의 shape속성은 튜플이기 때문에 reshape 메서드에 이를 넘기는 것도 가능하다.

In [24]:
arr=np.arange(15).reshape((5,3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [25]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

다차원 배열을 낮은 차원으로 변환하는 것을 평탄화라고 한다.원본 데이터의 복사본을 생성하지 않는다.

In [26]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [27]:
arr.flatten()
# flatten 메서드는 ravel메서드와 유사하게 동작하지만 데이터의 복사본을 반환

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

A.2.2 C순서와 포트란 순서

로우와 컬럼 우선 순서는 각각 C순서와 포트란 순서로 알려져 있다.

In [28]:
arr=np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
arr.ravel('C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

로우 우선: C순서 상위 차원을 우선 탐색한다. 1번 축을 0번 축보다 우선 탐색한다.

In [31]:
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

컬럼 우선: 포트란 순서 상위 차원을 나중에 탐색한다. 0번 축을 1번 축보다 우선 탐색한다.

A.2.3 배열 이어붙이고 나누기

In [32]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

concatenate는 매열의 목록(튜플, 리스트등)을 받아서 주어진 축에 따라서 하나의 배열로 합쳐준다

In [33]:
arr2=np.array([[7,8,9],[10,11,12]])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [34]:
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [35]:
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

vstack, hstack메서트를 사용해서 쉽게 할 수도 있음

In [36]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [38]:
arr=np.random.randn(5,2)
arr

array([[-0.52224927,  0.81850932],
       [ 0.59269854,  1.76305625],
       [ 1.28943228,  1.34497584],
       [ 0.62533562, -1.65389657],
       [-0.1085907 , -0.99068988]])

In [39]:
first,second,third=np.split(arr,[1,3])

[1,3]은 배열을 나눌 대 기준이 되는 위치를 나타낸다.

In [40]:
first

array([[-0.52224927,  0.81850932]])

In [41]:
second

array([[0.59269854, 1.76305625],
       [1.28943228, 1.34497584]])

In [42]:
third

array([[ 0.62533562, -1.65389657],
       [-0.1085907 , -0.99068988]])

배열 쌓기 도우미: r_과 c_

In [43]:
arr=np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [44]:
arr1=arr.reshape((3,2))
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [45]:
arr2=np.random.randn(3,2)
arr2

array([[ 1.39942999,  1.37051122],
       [-0.31084685, -1.49108117],
       [ 1.07936522, -0.06299435]])

In [46]:
np.r_[arr1,arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [ 1.39942999,  1.37051122],
       [-0.31084685, -1.49108117],
       [ 1.07936522, -0.06299435]])

In [47]:
np.c_[np.r_[arr1,arr2],arr]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [ 1.39942999,  1.37051122,  3.        ],
       [-0.31084685, -1.49108117,  4.        ],
       [ 1.07936522, -0.06299435,  5.        ]])

In [48]:
np.c_[1:6,-10:-5]
# 슬라이스를 배열로 변환해준다.

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

A.2.4 원소 반복하기: repeat과 tile

In [49]:
arr=np.arange(3)
arr

array([0, 1, 2])

In [50]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

기본적으로 정수를 넘기면 각 배열은 그 수 만큼 반복된다.

In [51]:
arr.repeat([2,3,4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

정수의 배열을 넘긴다면 각 원손는 배열에 담긴 정수만큼 반복

In [52]:
# 다차원 배열의 경우 특정 축을 따라 각 원소가 반복된다.
arr=np.random.randn(2,2)
arr

array([[ 0.47606022, -0.37203466],
       [ 0.68152238,  0.0905015 ]])

In [53]:
arr.repeat(2,axis=0)

array([[ 0.47606022, -0.37203466],
       [ 0.47606022, -0.37203466],
       [ 0.68152238,  0.0905015 ],
       [ 0.68152238,  0.0905015 ]])

In [54]:
arr.repeat([2,3],axis=0)

array([[ 0.47606022, -0.37203466],
       [ 0.47606022, -0.37203466],
       [ 0.68152238,  0.0905015 ],
       [ 0.68152238,  0.0905015 ],
       [ 0.68152238,  0.0905015 ]])

In [55]:
arr.repeat([2,3],axis=1)

array([[ 0.47606022,  0.47606022, -0.37203466, -0.37203466, -0.37203466],
       [ 0.68152238,  0.68152238,  0.0905015 ,  0.0905015 ,  0.0905015 ]])

In [56]:
arr.repeat(2)
# axis인지를 넘기지 않으면 평탄화 된다.

array([ 0.47606022,  0.47606022, -0.37203466, -0.37203466,  0.68152238,
        0.68152238,  0.0905015 ,  0.0905015 ])

In [57]:
arr

array([[ 0.47606022, -0.37203466],
       [ 0.68152238,  0.0905015 ]])

In [58]:
np.tile(arr,2)
# tile메서드는 축을 따라서 배열을 복사해서 쌓는 함수

array([[ 0.47606022, -0.37203466,  0.47606022, -0.37203466],
       [ 0.68152238,  0.0905015 ,  0.68152238,  0.0905015 ]])

In [59]:
np.tile(arr,(2,1))

array([[ 0.47606022, -0.37203466],
       [ 0.68152238,  0.0905015 ],
       [ 0.47606022, -0.37203466],
       [ 0.68152238,  0.0905015 ]])

tile메서드의 두 번째 인자는 타일을 이어 붙일 모양을 나타내는 튜플이 될 수 있다.

In [60]:
np.tile(arr,(3,2))

array([[ 0.47606022, -0.37203466,  0.47606022, -0.37203466],
       [ 0.68152238,  0.0905015 ,  0.68152238,  0.0905015 ],
       [ 0.47606022, -0.37203466,  0.47606022, -0.37203466],
       [ 0.68152238,  0.0905015 ,  0.68152238,  0.0905015 ],
       [ 0.47606022, -0.37203466,  0.47606022, -0.37203466],
       [ 0.68152238,  0.0905015 ,  0.68152238,  0.0905015 ]])

A.2.5 팬시 색인: take와 put

In [61]:
arr=np.arange(10)*100
arr

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [62]:
inds=[7,1,2,6]

In [63]:
arr[inds]

array([700, 100, 200, 600])

정수 배열을 사용한 팬시 색인 기능을 통해 배열의 일부값을 지정하거나 가져올 수 있다.

In [64]:
arr.take(inds)

array([700, 100, 200, 600])

In [65]:
arr.put(inds,42)
arr
# inds 부분에 42를 넣음

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [66]:
arr.put(inds,[40,41,42,43])
arr
# inds 부분에 차례로 넣음

array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

In [67]:
inds =[2,0,2,1]

In [68]:
arr=np.random.randn(2,4)
arr

array([[ 0.81024458,  0.00530119, -0.44714583, -0.74748199],
       [-0.14213824,  1.22863523, -1.78730213,  0.91461125]])

In [69]:
arr.take(inds,axis=1)

array([[-0.44714583,  0.81024458, -0.44714583,  0.00530119],
       [-1.78730213, -0.14213824, -1.78730213,  1.22863523]])

A.3 브로드 캐스팅

In [70]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [71]:
arr*4

array([ 0,  4,  8, 12, 16])

여기서 스칼라 값 4는 곱셈 연산 과정에서 배열의 모든 원소로 브로드캐스트 됐다

In [72]:
arr=np.random.rand(4,3)
arr

array([[0.15272933, 0.46795312, 0.06512914],
       [0.89228971, 0.11555545, 0.01238624],
       [0.74775293, 0.94823709, 0.55490903],
       [0.63417543, 0.27608015, 0.83996631]])

In [73]:
arr.mean(0)

array([0.60673685, 0.45195645, 0.36809768])

In [74]:
demeaned=arr-arr.mean(0)
demeaned

array([[-0.45400752,  0.01599667, -0.30296854],
       [ 0.28555286, -0.33640101, -0.35571144],
       [ 0.14101608,  0.49628064,  0.18681135],
       [ 0.02743858, -0.17587631,  0.47186863]])

In [75]:
demeaned.mean(0)

array([ 8.32667268e-17,  2.77555756e-17, -2.77555756e-17])

브로드 캐스팅 규칙

만일 이어지는 각 차원(시작과 끝까지)에 대해 축의 길이가 일치하거나 둘 중 하나의 길이가 1이라면 두 배열은 브로드캐스팅 호환이다. 브로드캐스팅은 누락된 혹은 길이가 1인 차원에 대해 수행된다.

In [76]:
arr

array([[0.15272933, 0.46795312, 0.06512914],
       [0.89228971, 0.11555545, 0.01238624],
       [0.74775293, 0.94823709, 0.55490903],
       [0.63417543, 0.27608015, 0.83996631]])

In [77]:
row_means=arr.mean(1)
row_means

array([0.22860387, 0.34007713, 0.75029969, 0.5834073 ])

In [78]:
row_means.shape

(4,)

In [79]:
row_means.reshape((4,1))

array([[0.22860387],
       [0.34007713],
       [0.75029969],
       [0.5834073 ]])

In [80]:
demeaned=arr-row_means.reshape((4,1))
demeaned

array([[-0.07587454,  0.23934926, -0.16347472],
       [ 0.55221258, -0.22452169, -0.32769089],
       [-0.00254676,  0.19793741, -0.19539065],
       [ 0.05076813, -0.30732715,  0.25655902]])

In [81]:
demeaned.mean(1)

array([-9.25185854e-18, -3.70074342e-17,  7.40148683e-17,  0.00000000e+00])

A.3.1 다른 축에 대해 브로드캐스팅하기

In [82]:
arr

array([[0.15272933, 0.46795312, 0.06512914],
       [0.89228971, 0.11555545, 0.01238624],
       [0.74775293, 0.94823709, 0.55490903],
       [0.63417543, 0.27608015, 0.83996631]])

In [83]:
arr.mean(1)

array([0.22860387, 0.34007713, 0.75029969, 0.5834073 ])

In [135]:
arr-arr.mean(1)

ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

In [85]:
arr.mean(1).reshape((4,1))

array([[0.22860387],
       [0.34007713],
       [0.75029969],
       [0.5834073 ]])

In [86]:
arr-arr.mean(1).reshape((4,1))

array([[-0.07587454,  0.23934926, -0.16347472],
       [ 0.55221258, -0.22452169, -0.32769089],
       [-0.00254676,  0.19793741, -0.19539065],
       [ 0.05076813, -0.30732715,  0.25655902]])

In [87]:
arr=np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [88]:
arr_3d=arr[:,np.newaxis,:]
arr_3d

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [89]:
arr_3d.shape

(4, 1, 4)

In [90]:
arr_1d=np.random.normal(size=3)
arr_1d

array([-0.333068  ,  0.19758584,  0.41559027])

In [91]:
arr_1d[:,np.newaxis]

array([[-0.333068  ],
       [ 0.19758584],
       [ 0.41559027]])

In [92]:
arr=np.random.randn(3,4,5)

In [93]:
depth_means=arr.mean(2)
depth_means
# 2번 축의 평균값

array([[-0.27232612, -0.1210431 , -0.1624794 , -0.26682357],
       [ 0.45239043, -0.40015295,  0.08712525,  0.2711284 ],
       [ 0.26409547, -0.68372281, -0.22482871,  0.57523693]])

In [94]:
depth_means.shape

(3, 4)

In [95]:
demeaned=arr-depth_means[:,:,np.newaxis]

In [96]:
demeaned.mean(2)

array([[-4.44089210e-17,  1.77635684e-16,  4.44089210e-17,
         4.44089210e-17],
       [ 4.44089210e-17,  0.00000000e+00,  0.00000000e+00,
         1.11022302e-17],
       [ 2.22044605e-17, -4.44089210e-17, -2.22044605e-17,
         8.88178420e-17]])

A.3.2 브로드캐스팅을 이용해서 배열에 값 대입하기

In [97]:
arr=np.zeros((4,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [98]:
arr[:]=5
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [99]:
col=np.array([1.28,-0.42,0.44,1.6])
col

array([ 1.28, -0.42,  0.44,  1.6 ])

In [100]:
arr[:]=col[:,np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [101]:
arr[:2]=[[-1.37],[0.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

A.4 고급 ufunc 사용법

A.4.1 ufunc 인스턴스 메서드

In [102]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
np.add.reduce(arr)
# reduce는 하나의 배열을 받아서 순차적인 이항 연산을 통해 축에 따라 그 값을 집계해준다.

45

In [104]:
arr.sum()

45

In [105]:
np.random.seed(12346) # 동일한 난수 발생을 위해 시드값 직접 지정

In [106]:
arr=np.random.randn(5,5)

In [107]:
arr[::2].sort(1) # 일부 로우를 정렬

In [108]:
arr[:,:-1]<arr[:,1:]

array([[ True,  True,  True,  True],
       [False,  True, False, False],
       [ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]])

아래는 이해를 위해 해봄

In [109]:
a=np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [110]:
a=a.reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [111]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [112]:
a[::2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [113]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [114]:
a[:,:-1]

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18],
       [20, 21, 22, 23]])

In [115]:
a[:,1:]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

여기까지

In [116]:
np.logical_and.reduce(arr[:,:-1]<arr[:,1:],axis=1)

array([ True, False,  True, False,  True])

In [117]:
arr=np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [118]:
np.add.accumulate(arr,axis=1)
# 누계

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]], dtype=int32)

In [119]:
arr=np.arange(3).repeat([1,2,2])
arr

array([0, 1, 1, 2, 2])

In [120]:
np.multiply.outer(arr,np.arange(5))
# oute메서드는 두 배열간의 외적을 계산한다.

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [121]:
x,y=np.random.randn(3,4),np.random.randn(5)

In [122]:
x.shape

(3, 4)

In [123]:
y.shape

(5,)

In [124]:
result=np.subtract.outer(x,y)
result.shape

(3, 4, 5)

In [125]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
np.add.reduceat(arr,[0,5,8])
# 이 결과는 arr[0:5],arr[5:8],arr[8:]에 대한 수행결과(합)

array([10, 18, 17], dtype=int32)

In [127]:
arr=np.multiply.outer(np.arange(4),np.arange(5))
arr

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [128]:
np.add.reduceat(arr,[0,2,4],axis=1)

array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]], dtype=int32)

A.4.2 파이썬으로 사용자 정의 ufunc 작성하기

In [129]:
def add_elements(x,y):
    return x+y

In [130]:
add_them=np.frompyfunc(add_elements,2,1)

In [131]:
add_them(np.arange(8),np.arange(8))
# frompyfunc을 이용해서 생성한 함수는 파이선 객체가 담긴 배열을 반환

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

In [132]:
add_them=np.vectorize(add_elements,otypes=[np.float64])

In [133]:
add_them(np.arange(8),np.arange(8))

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])